[package]
name = "ids_rust"
version = "0.1.0"
authors = ["wareya <wareya@gmail.com>"]

[dependencies]
rouille = "2.2.0"
url = "1"

[dependencies.regex]
version = "1.3.1"
default-features = false
features = ["std"]